### ISSUE TITLE
he term 'Register-ScheduledJob' is not recognized as the name of a cmdlet....

### ISSUE THREAD

**Issue by amnich** [mkellerman/Invoke-CommandAs#1]
add 'Import-Module PSScheduledJob' inside the scriptblock of invoke-command cos it throws an exception:

    The term 'Register-ScheduledJob' is not recognized as the name of a cmdlet, function, script file, or 
    operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mkellerman** [comment]
What version of Powershell are you trying to run this on? And what OS?

**Comment by mkellerman** [comment]
After some testing, I believe the minimum requirement for this script would be PowerShell 3.0 on the remote machine.
