### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by manikandanid** [mkellerman/Invoke-CommandAs#12]
I am getting the following error while running the command 

You cannot call a method on a null-valued expression.
At S:\Philips\Apps\iSite\Tools\SHDBAutoDeployService\Sensors\Content\Invoke-CommandAs.psm1:194 char:59
+                 $UsingVariables = $ScriptBlock.ast.FindAll <<<< ({$args[0] -is [System.Management.Automation.Language
.UsingExpressionAst]},$True)
    + CategoryInfo          : InvalidOperation: (FindAll:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

![image](https://user-images.githubusercontent.com/3234685/46881989-d4fce980-ce6a-11e8-8530-72cad150017b.png)

**Comment by mkellerman** [comment]
What version of Powershell are you running on?

````
$PSVersionTable
````

What version of the module are you running?

````
Get-Module -Name Invoke-CommandAs
````

And how did you install the module? from the Powershell Gallery? or from GitHub?

**Comment by manikandanid** [comment]
My version is 2.0

![image](https://user-images.githubusercontent.com/3234685/46953552-ce10e980-d0ab-11e8-881b-2ba8c1e2b87a.png)

I just d/w the psm1 to local path where my other scripts are located and refrenced it via import module.

**Comment by mkellerman** [comment]
Sorry, you need v3 or higher

**Comment by manikandanid** [comment]
Thanks and please add the same info in set of system requirements. So that this does not occur. BTW your script is great and handy but i cant use it due to version mismatch.

**Comment by mkellerman** [comment]
Thanks! Will do!

Sent from my iPhone

On Oct 15, 2018, at 7:29 AM, manikandanid <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks and please add the same info in set of system requirements. So that this does not occur. BTW your script is great and handy but i cant use it due to version mismatch.
