### ISSUE TITLE
Issue with Windows 7 machines

### ISSUE THREAD

**Issue by dfranciscus** [mkellerman/Invoke-CommandAs#15]
When I run the command below against Windows 7 machines I am getting this error. I believe this used to happen in an earlier version.

 C:\Scripts\PowerShell> invoke-commandas -ComputerName hslllp2 -ScriptBlock {choco list -lo} -AsSystem
The term 'Get-ScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-ScheduledTask
    + PSComputerName        : hslllp2

**Comment by mkellerman** [comment]
I'll need a test VM to play with, but try and comment out line:
https://github.com/mkellerman/Invoke-CommandAs/blob/master/Invoke-CommandAs/Private/Invoke-ScheduledTask.ps1#L136

See if it works, and at the same time, make sure that the ScheduledTask get's removed correctly please.

**Comment by mkellerman** [comment]
Created a W2008R2 vm to test with. i think there might be an issue with more lines than just L136, i'll investigate.

**Comment by dfranciscus** [comment]
Thanks! I’m home today so can’t really test until Monday probably.

**Comment by mkellerman** [comment]
I got a W2008R2 and a W2012R2 machine for testing.

At the moment, W2008R2 with PSv2.0 fails horribly. I just had to test it.. 🤣 
I'm upgrading the VM to run with PSv3.0 now, and will be able to test more in the morning.

I did tones of rework to the script, and did some major stability improvements on W2012R2.

**Comment by mkellerman** [comment]
I'm wondering what is the lowest version of PS I'm trying to support at this point.
What version are you running in your environment?

**Comment by mkellerman** [comment]
Got it to work on Windows Server 2008 R2 + PS3.0

It should work fine on Windows 7, but will need you to test!

**Comment by mkellerman** [comment]
Version 3.1.0 published to PSGallery
Fixed #18
