### ISSUE TITLE
One liner in README doesn't work

### ISSUE THREAD

**Issue by bulanula** [mkellerman/Invoke-CommandAs#19]
Hi, 

Appreciate your work with this, it's a very good script. 

A very minor issue propped up recently due to what I believe is the splitting of the script into Public and Private directories. I've attached an image showing the problem.

This one liner, which I got from the helpful documentation, `(New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/mkellerman/Invoke-CommandAs/master/Invoke-CommandAs.psm1") | iex` used to work very well a few days ago but is no longer working as of today. I tend to use it as it's very portable and doesn't require me to download the whole repo etc.

I've resorted to using the following workaround relying on the old, deleted file version but this isn't ideal as I'd like to be on the latest version of the script: `(New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/mkellerman/Invoke-CommandAs/f40ecf69a33d0cffae88d3370d5ee2a8240afd47/Invoke-CommandAs.psm1") | iex`

It would be great if we can please have a working one liner solution for this if possible, many thanks for all your hard work !

![image](https://user-images.githubusercontent.com/40326489/52522930-77937080-2c83-11e9-9e8e-d3e7f4bfeb9d.png)

**Comment by mkellerman** [comment]
I have to admit, I prefer having 1 single file to import as well.

And since we don’t have many functions, might as well keep it light and simple.

I’ll see what I can do to put it back together into one single file.

**Comment by mkellerman** [comment]
Closed #25
