### ISSUE TITLE
Pass a filepath parameter like invoke-command 

### ISSUE THREAD

**Issue by weiyentan** [mkellerman/Invoke-CommandAs#20]
Suggestion is to provide an option to use a parameter called file path which I can run a script as another user

**Comment by mkellerman** [comment]
Great idea! Will implement on next version!

**Comment by mkellerman** [comment]
I've just pushed the changes to master. Can you pull a copy from GitHub and test? I'm now replicating ALL parameters from Invoke-Command.

**Comment by mkellerman** [comment]
Fixed. Invoke-CommandAs has all the same properties than the real Invoke-Command function.
