### ISSUE TITLE
Add '-UseSSL' Parameter

### ISSUE THREAD

**Issue by adilio** [mkellerman/Invoke-CommandAs#23]
In our Production environment, we have set `winrm quickconfig -transport:https`, in order to only enable the HTTPS WSMan listener (cert-based transport).

As such, when running, `Invoke-Command`, we must specify the `-UseSSL` parameter.

It would be awesome if we could also use a similar `-UseSSL` parameter in `Invoke-CommandAs`, as well.

Currently, we can do the following:
```powershell
$Sess = New-PSSession -ComputerName FQDN.ubc.ca  -UseSSL
Invoke-CommandAs -Session $Sess -ScriptBlock { Get-Process } -AsSystem
```

This would just mean one less step on instantiating the PSSession.

Merci beaucoup!

**Comment by mkellerman** [comment]
I've just pushed the changes to master. Can you pull a copy from GitHub and test? I'm now replicating ALL parameters from Invoke-Command.

**Comment by adilio** [comment]
It works!

Tested on:
- Windows 10 1809
- Windows Server 2019

Side-note: I did get the error:
```
Invoke-CommandAs : A parameter cannot be found that matches parameter name 'RunElevated'.
```

Works fine when I remove that parameter. Is `-RunElevated` now deprecated, or just not needed with `-AsSystem`?

**Comment by mkellerman** [comment]
Yeah, Im running all commands as elevated. :/

No sure if that parameter is ever NOT going to be used.

What are your thoughts?

**Comment by adilio** [comment]
Makes sense to me, running as elevated is kinda the whole point of the module.

LGTM!
