### ISSUE TITLE
One liner in README still seems to have trouble

### ISSUE THREAD

**Issue by bulanula** [mkellerman/Invoke-CommandAs#27]
Hi, 

Thanks for closing https://github.com/mkellerman/Invoke-CommandAs/issues/19. Not sure what the etiquette with this is, please let me know if it would have been better to make a comment on the old issue rather than opening this new one.

However, I'm still having trouble getting the one liner (`(New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/mkellerman/Invoke-CommandAs/master/Scripts/Invoke-CommandAs.ps1") | iex`) to work well, as the screenshot below shows:

![image](https://user-images.githubusercontent.com/40326489/54085393-82e6c400-4335-11e9-9fd2-0e810a697a51.png)

Many thanks for your help with this, much appreciated !

**Comment by mkellerman** [comment]
I really want this to work for you, but it's a lot of work.. lol.

If anyone know an easy way to make a multiple file ps1 module, and yet, produce a single ps1 for fast single file import, let me know.

**Comment by mkellerman** [comment]
I have updated it to work with 2 OneLiners.. lol.. best i could do for now!

**Comment by mkellerman** [comment]
Improved it to be only 1 line, and removed the Invoke-Expression, which can be blocked on most environments.

```
"Public/Invoke-CommandAs.ps1", "Private/Invoke-ScheduledTask.ps1" | % {
    . ([ScriptBlock]::Create((New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/mkellerman/Invoke-CommandAs/master/Invoke-CommandAs/${_}")))
}
```
