### ISSUE TITLE
Windows 7 - Run with Highest Privileges

### ISSUE THREAD

**Issue by jyonke** [mkellerman/Invoke-CommandAs#28]
PSVersion - 5.1.14409.1018
OSVersion - 6.1.7601.65536
ModuleVersion - 3.1.2

I am seeing an issue where none of the scheduled tasks are set to run with highest privileges on Windows 7 (Have not spun up a 2k8r2 server yet to test). If I need to execute something only on the local machine, running as SYSTEM alleviates this. When I need to run as a specific user for network share access I can not execute as administrator, as this option is not set.

**Comment by mkellerman** [comment]
Should be resolved with -RunElevated property. Fixed #35
