### ISSUE TITLE
Removal of RunElevated Parameter

### ISSUE THREAD

**Issue by nerddtvg** [mkellerman/Invoke-CommandAs#30]
In commit b07e37198f1cab58ab2154aee8a76c4303bd900f, why was the RunElevated parameter removed?

This is also still referenced in the README.md file.

**Comment by mkellerman** [comment]
Oversight. I need to re-add it.

**Comment by nerddtvg** [comment]
Thank you!

**Comment by mkellerman** [comment]
Resolved #35
