### ISSUE TITLE
Removing entries from the Task Scheduler log

### ISSUE THREAD

**Issue by dfranciscus** [mkellerman/Invoke-CommandAs#39]
I use the -AsSystem often and I see that creates a new task each time so on my clients the Task Scheduler log is filling up with old entries. For now I will think of a way to clear these out myself but maybe there is something that can be done to remove these automatically?  Just spit balling here.

**Comment by mkellerman** [comment]
Cleanup should be happening. You should not be seeing a task lingering there once it ran.

See: 
https://github.com/mkellerman/Invoke-CommandAs/blob/0a06b617ee21424d0650455efab628310fdd838a/Invoke-CommandAs/Private/Invoke-ScheduledTask.ps1#L192

What OS/PSVersion are you running this from and to? What version of the module are you using?

**Comment by dfranciscus** [comment]
Ah maybe its the module version. I was using 2.2 could that be it? I had some issues with newer ones a while back and didnt have time to figure out what the issue was. I can try again.

**Comment by mkellerman** [comment]
Yeah, it should be all fixed now!
Please report back if the problem persists or if there is any new issues with your use case.
