### ISSUE TITLE
AsSystem doesn't seem to execute while device is on battery power

### ISSUE THREAD

**Issue by TheBlackAdderDK** [mkellerman/Invoke-CommandAs#51]
Hi
I'm trying to execute some scripts, order to display some popups in the users session - and I have succeeded in this, by using the -AsSystem and combining with RunAsUser.

But... it only works, when the laptop is not on batterypower.

I can run an whoami on batterypower as my self, but as soon as the AsUser flag is added it fails on battery only.

Best regards
Flemming

**Comment by mkellerman** [comment]
I just merged a PR that might fix your issue. Please try with the latest version from GitHub.

**Comment by TheBlackAdderDK** [comment]
Hi Marc

The file you have changed seems to be Invoke-ScheduledTask.ps1 - my problem is with Invoke-CommandAs?

Best regards
Flemming

**Comment by mkellerman** [comment]
Try it please.

**Comment by TheBlackAdderDK** [comment]
Hi Marc 
Guess I wasn't clear enough - did try to download and replace the Invoke-ScheduledTask.ps1 file, but without any luck.

Sorry if I wasn't clear about that.


Best regards
Flemming

**Comment by mkellerman** [comment]
Closed due to inactivity
