### ISSUE TITLE
Would it be possible to run -AsLocalService

### ISSUE THREAD

**Issue by sebatminalea** [mkellerman/Invoke-CommandAs#52]
I'd like to invoke as NT AUTHORITY\LOCAL SERVICE instead of System which has a bit too much power for what I need.

I tried to implement it myself but it doesn't seem to work -- likely because the local service cannot create scheduled tasks or something like that? I'm a bit out of my comfort zone here :-) Is there a workaround?

**Comment by mkellerman** [comment]
Is this something you're able to do locally? create a schedule tasks using LOCAL SERVICE? i dont have the environment to test this.

**Comment by mkellerman** [comment]
Closed due to inactivity
