### ISSUE TITLE
Add tagging to Azure pipeline for releases

### ISSUE THREAD

**Issue by krystofwoldrich** [mkellerman/Invoke-CommandAs#58]
Hi guys,
I really apriciete the possibility to download this module directly from GitHub. But since there are no tags here, I have to search appropriet commit hashes to ensure I always download correct version of this module in my CI pipelines.

Would you consider taging the releases? Thank you in advance for any response.

**Comment by mkellerman** [comment]
I created a tag manually for you for now. Hope this helps. But would be good that this step is automagically done with the pipeline. Will investigate further when I can.

(Sorry for the delay, I was on vacation for a week)

**Comment by krystofwoldrich** [comment]
Thank you,
yes, it helps.

**Comment by mkellerman** [comment]
Closed due to inactivity
