### ISSUE TITLE
parsing error when using -FilePath

### ISSUE THREAD

**Issue by kkawabanga** [mkellerman/Invoke-CommandAs#59]
https://github.com/mkellerman/Invoke-CommandAs/blob/222657169a66dc9f02edf707cb86e38a27e25f20/Invoke-CommandAs/Public/Invoke-CommandAs.ps1#L313

use "-raw" switch, otherwise "get-content" removes newline-characters from the scriptfile on import.

->

Line 313:             $ScriptContent = Get-Content -Path $FilePath **-Raw**

**Comment by mkellerman** [comment]
Thank you. Do you wish to create the PR and I merge it in? Let me know, or I'll go right ahead and make the changes.

**Comment by kkawabanga** [comment]
Pull request is ready to merge

**Comment by mkellerman** [comment]
#60 has been merge! thank you for your contribution!
