### ISSUE TITLE
Hide window when `-AsInteractive`

### ISSUE THREAD

**Issue by felipecrs** [mkellerman/Invoke-CommandAs#67]
Hi there. Thanks a ton for creating this.

I would like to know if it would be possible to hide the window which gets momentarily shown when the command is invoked with `-AsInteractive`.

For example, I'm trying to turn off my screen and lock my computer from a SSH session (I am creating an automation to do this whenever I leave my office room), and a window flashes during the execution of the command:

https://github.com/user-attachments/assets/1cca1299-5218-43b8-a925-b40e810e58d8

Being able to hide this window would make the experience perfect. :)

**Comment by mkellerman** [comment]
Hi @felipecrs,
This is an unfortunate behaviour of PowerShell. There might be a way to it using `.vbs`, but that would be a whole different solution altogether.

Source: https://www.reddit.com/r/PowerShell/comments/18cp5ur/task_scheduler_windowstyle_hidden_minimized/

**Comment by felipecrs** [comment]
I see. Thank you very much for the answer!
